/********************************************************************************
 * \copyright
 * Copyright 2009-2017, Card Reader Factory.  All rights were reserved.
 * From 2018 this code has been made PUBLIC DOMAIN.
 * This means that there are no longer any ownership rights such as copyright, trademark, or patent over this code.
 * This code can be modified, distributed, or sold even without any attribution by anyone.
 *
 * We would however be very grateful to anyone using this code in their product if you could add the line below into your product's documentation:
 * Special thanks to Nicholas Alexander Michael Webber, Terry Botten & all the staff working for Operation (Police) Academy. Without these people this code would not have been made public and the existance of this very product would be very much in doubt.
 *
 *******************************************************************************/

//==============================================================================
// File:           bootldr.h
// Compiler:       GCC Atmel AVR C Compiler
// Output Size:    -
// Created:        Wed Sep 08 00:29:12 2010

//
// Description:    This file is generated by 'create' tool and is to be included
//                 in the 'bootldr' project. It contains the settings to
//                 configure the boot loader according to the configurations
//                 used in the encrypted file.
//==============================================================================


#ifndef bootldr_h
#define bootldr_h


#define PAGE_SIZE 128
#define MEM_SIZE 28672
#define CRC_CHECK
#define SIGNATURE 0x105D3CBD
#define BUFFER_SIZE 148
#define INITIALVECTOR_3 0xBC380F19
#define INITIALVECTOR_2 0xFB41DE29
#define INITIALVECTOR_1 0x955A1D11
#define INITIALVECTOR_0 0x2AF67E8F
#define KEY_COUNT 3


#endif // bootldr_h
