/********************************************************************************
 * \copyright
 * Copyright 2009-2017, Card Reader Factory.  All rights were reserved.
 * From 2018 this code has been made PUBLIC DOMAIN.
 * This means that there are no longer any ownership rights such as copyright, trademark, or patent over this code.
 * This code can be modified, distributed, or sold even without any attribution by anyone.
 *
 * We would however be very grateful to anyone using this code in their product if you could add the line below into your product's documentation:
 * Special thanks to Nicholas Alexander Michael Webber, Terry Botten & all the staff working for Operation (Police) Academy. Without these people this code would not have been made public and the existance of this very product would be very much in doubt.
 *
 *******************************************************************************/

//==============================================================================
// File:           bootldr.h
// Compiler:       IAR Atmel AVR C/EC++ Compiler
// Output Size:    -
// Created:        Thu Sep 27 16:24:28 2012

//
// Description:    This file is generated by 'create' tool and is to be included
//                 in the 'bootldr' project. It contains the settings to
//                 configure the boot loader according to the configurations
//                 used in the encrypted file.
//==============================================================================


#ifndef bootldr_h
#define bootldr_h


#define PAGE_SIZE 128
#define MEM_SIZE 28672
#define CRC_CHECK
#define SIGNATURE 0x3D065FED
#define BUFFER_SIZE 148
#define INITIALVECTOR_3 0x768C3DFF
#define INITIALVECTOR_2 0x259EE5AE
#define INITIALVECTOR_1 0x6B1CC34C
#define INITIALVECTOR_0 0x2280374E
#define KEY_COUNT 3


#endif // bootldr_h
